/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  pembukaanSidebar: {
    'Pembukaan': ['pengantar', 'intro', 'prima'],
    'Modul': ['modul','setupmodul']
  },

  docs: [
    {
      type: 'category',
      label: 'Backoffice',
      collapsible: false,
      collapsed: true,
      items: [
        {
          type: 'category',
          collapsed: false,
          label: 'kasir',
          items: ['kasir/intro'],
        },
        {
          type: 'category',
          collapsed: false,
          label: 'e-mr',
          items: ['e-mr/intro','e-mr/smpk','e-mr/master'],
        },
        {
          type: 'category',
          collapsed: false,
          label: 'e-office',
          items: ['e-office/intro','e-office/master','e-office/setupsurat'],
        },
        {
          type: 'category',
          collapsed: false,
          label: 'humas',
          items: ['humas/intro','humas/kerjasama','humas/keluhan'],
        },
        {
          type: 'category',
          collapsed: false,
          label: 'kegiatan',
          items: ['kegiatan/intro'],
        },
      ],
    },
    {
      type: 'ref',
      id: 'modul', // Document id (string).
    },
  ],

  penunjang: [
  {
    "Penunjang": ["penunjang/intro","penunjang/darah","penunjang/jenazah","penunjang/gizi","penunjang/visum","penunjang/poct"],
    "Halaman Depan":
      [
        {
          type: 'ref',
          id: 'modul', // Document id (string).
        },
        {
          type: 'ref',
          id: 'setupmodul', // Document id (string).
        }
      ]
    },
  ],

  troubleshoting: [
  {
    "Troubleshoting": ["server/intro","server/penuh","server/pcclient","server/printersetup"],
    "Halaman Depan":
      [
        {
          type: 'ref',
          id: 'modul', // Document id (string).
        },
        {
          type: 'ref',
          id: 'setupmodul', // Document id (string).
        }
      ]
    },
  ],

  uncategorize: [
    {
      "Uncategorize": ["penelitian/obat"],
      "Halaman Depan":
        [
          {
            type: 'ref',
            id: 'modul', // Document id (string).
          },
          {
            type: 'ref',
            id: 'setupmodul', // Document id (string).
          }
        ]
      },
    ],

  publikSidebar: {
    "Aplikasi Publik": [
      {
        "Pendaftaran Online": [ "publik/daftar-gp","publik/daftar-rajal","publik/daftar-mcu","publik/daftar-vaksin"],
      },
      "publik/sdm-ol","publik/bankdarah-ol","publik/survei","publik/cari-dokter","publik/keluhan-pelanggan",
    ],
    "Aplikasi Internal": ["whatsapp/viaaplikasi","whatsapp/viamodul"],
    "Aplikasi Pendukung" : ["rekammedis/koreksil14l15","whatsapp/autobot","notifikasi/prima"],
    "Vendor": ['vendor/kios','vendor/sismadak','vendor/dms'],
    "Halaman Depan": [
      {
        type: 'ref',
        id: 'modul', // Document id (string).
      },
      {
        type: 'ref',
        id: 'setupmodul', // Document id (string).
      }
    ]
  },
};
